[OPTIONS]
Contents file=C:\Users\analyticsearch\Downloads\Viewhlp\viewhlp.hhc
[FILES]
C:\Users\analyticsearch\Downloads\Viewhlp\main.htm
C:\Users\analyticsearch\Downloads\Viewhlp\$WWAssociativeLinks\Property
C:\Users\analyticsearch\Downloads\Viewhlp\$WWKeywordLinks\BTree
C:\Users\analyticsearch\Downloads\Viewhlp\$WWKeywordLinks\Data
C:\Users\analyticsearch\Downloads\Viewhlp\$WWKeywordLinks\Map
C:\Users\analyticsearch\Downloads\Viewhlp\$WWKeywordLinks\Property
C:\Users\analyticsearch\Downloads\Viewhlp\#IDXHDR
C:\Users\analyticsearch\Downloads\Viewhlp\#ITBITS
C:\Users\analyticsearch\Downloads\Viewhlp\#STRINGS
C:\Users\analyticsearch\Downloads\Viewhlp\#SYSTEM
C:\Users\analyticsearch\Downloads\Viewhlp\#TOPICS
C:\Users\analyticsearch\Downloads\Viewhlp\#URLSTR
C:\Users\analyticsearch\Downloads\Viewhlp\#URLTBL
C:\Users\analyticsearch\Downloads\Viewhlp\#WINDOWS
C:\Users\analyticsearch\Downloads\Viewhlp\$FIftiMain
C:\Users\analyticsearch\Downloads\Viewhlp\$OBJINST
C:\Users\analyticsearch\Downloads\Viewhlp\accessibility.htm
C:\Users\analyticsearch\Downloads\Viewhlp\advanced.htm
C:\Users\analyticsearch\Downloads\Viewhlp\basic.htm
C:\Users\analyticsearch\Downloads\Viewhlp\bool.gif
C:\Users\analyticsearch\Downloads\Viewhlp\bool.htm
C:\Users\analyticsearch\Downloads\Viewhlp\changes.htm
C:\Users\analyticsearch\Downloads\Viewhlp\color.htm
C:\Users\analyticsearch\Downloads\Viewhlp\copy.htm
C:\Users\analyticsearch\Downloads\Viewhlp\cshelp.gif
C:\Users\analyticsearch\Downloads\Viewhlp\custom.htm
C:\Users\analyticsearch\Downloads\Viewhlp\db.htm
C:\Users\analyticsearch\Downloads\Viewhlp\decompile.htm
C:\Users\analyticsearch\Downloads\Viewhlp\disability.htm
C:\Users\analyticsearch\Downloads\Viewhlp\favs.htm
C:\Users\analyticsearch\Downloads\Viewhlp\font.htm
C:\Users\analyticsearch\Downloads\Viewhlp\fts.htm
C:\Users\analyticsearch\Downloads\Viewhlp\ftsover.htm
C:\Users\analyticsearch\Downloads\Viewhlp\fts_simple.htm
C:\Users\analyticsearch\Downloads\Viewhlp\general.htm
C:\Users\analyticsearch\Downloads\Viewhlp\hide.htm
C:\Users\analyticsearch\Downloads\Viewhlp\highlt.htm
C:\Users\analyticsearch\Downloads\Viewhlp\more.htm
C:\Users\analyticsearch\Downloads\Viewhlp\mousekey.htm
C:\Users\analyticsearch\Downloads\Viewhlp\move.htm
C:\Users\analyticsearch\Downloads\Viewhlp\nest.htm
C:\Users\analyticsearch\Downloads\Viewhlp\onestep.gif
C:\Users\analyticsearch\Downloads\Viewhlp\overview.htm
C:\Users\analyticsearch\Downloads\Viewhlp\previous.htm
C:\Users\analyticsearch\Downloads\Viewhlp\print.htm
C:\Users\analyticsearch\Downloads\Viewhlp\shortcut.htm
C:\Users\analyticsearch\Downloads\Viewhlp\similar.htm
C:\Users\analyticsearch\Downloads\Viewhlp\titles.htm
C:\Users\analyticsearch\Downloads\Viewhlp\topic.htm
C:\Users\analyticsearch\Downloads\Viewhlp\viewer.gif
C:\Users\analyticsearch\Downloads\Viewhlp\viewer.hhk
C:\Users\analyticsearch\Downloads\Viewhlp\viewer.htm
C:\Users\analyticsearch\Downloads\Viewhlp\viewhlp.hhc
C:\Users\analyticsearch\Downloads\Viewhlp\Viewhlp.hhk
C:\Users\analyticsearch\Downloads\Viewhlp\wild.htm
C:\Users\analyticsearch\Downloads\Viewhlp\window.htm